format = """
[ ](bold)$all
"""
[directory]
style = "bold blue"

[git_branch]
style = "bold yellow"

[cmd_duration]
style = "bold cyan"

[package]
symbol = " "

[golang]
symbol = "ﳑ "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[python]
symbol = " "
style = "bold purple"

[dotnet]
format = "via [$symbol($version) ]($style)"
symbol = " "
