format = """
[ ](bold)$all
"""
[directory]
style = "bold blue"

[git_branch]
style = "bold yellow"

[cmd_duration]
style = "bold cyan"

[golang]
symbol = "ﳑ "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[python]
symbol = " "
style = "bold purple"
